### ISSUE TITLE
Cant import csv file correctly

### ISSUE THREAD

**Issue by victorjoel44** [iannuttall/binlist-data#11]
Hi do any of you have the bin data csv imported in sql server, or with the correct comas? cause some banks has comas in between and it lose format.

**Comment by ThejasIyer** [comment]
Hi, I am unable to download the csv file. When i click on download, it directs me to a site and has raw text data on that site. Kindly help me download the csv version of this bin list file. Thanks!

**Comment by iannuttall** [comment]
Hey, could you provide some examples of banks with commas in so I can check it?

**Comment by iannuttall** [comment]
Just had a look through and found a couple like https://ian.is/binlist/?bin=400222

These imported properly to phpMyAdmin for me.
