### ISSUE TITLE
Unable to download the csv file

### ISSUE THREAD

**Issue by ThejasIyer** [iannuttall/binlist-data#13]
Hi, I am unable to download the csv file. When i click on download, it directs me to a site and has raw text data on that site. Kindly help me download the csv version of this bin list file. Thanks!

**Comment by iannuttall** [comment]
Hey, best way to do it is just download the entire repository as a zip file by clicking on the Code button:

![image](https://user-images.githubusercontent.com/6681919/87138495-698db900-c296-11ea-95af-0cb0df8f8df0.png)

**Comment by ThejasIyer** [comment]
Thanks a lot!:)
