### ISSUE TITLE
BIN for Capital One and Bank of America are wrong

### ISSUE THREAD

**Issue by jorge-acosta-abstracta** [iannuttall/binlist-data#14]
Dear team, 

The following BIN are wrong:

510805
546633

Is this CSV out dated?

**Comment by iannuttall** [comment]
What is the correct info for those BINs? Can you provide a source link? Numbers get recycled all the time, so yes, the CSV is outdated ;)

**Comment by jorge-acosta-abstracta** [comment]
Sure, 

I'll provide a few I have handy:

510855 US Capital One Debit
379815 US American Express (Blue Cash) Credit
546633 US Bank of America Credit
514377 US Venmo|PayPal Debit (Issued by Bancorp Bank)
440393 US PayPal Debit
522915 US (TransferWise) Debit (Issued by Community Federal Savings Bank)

**Comment by iannuttall** [comment]
If you can provide a PR, I'll review this and merge :)
