### ISSUE TITLE
Is project abandoned

### ISSUE THREAD

**Issue by eduardev** [iannuttall/binlist-data#6]
Hi.

Has this project been abandoned?
Any tips on how to get it being updated?

**Comment by kingthorin** [comment]
@iannuttall I'd be willing to help you figure out a github action to do updates to the list. Or, help handle PRs if you need.

Edit: or both :wink:

**Comment by d3vr** [comment]
Maintainer doesn't seem to have been active for close to 10 months, maybe it's time to fork the project and keep a fork active ?

**Comment by iannuttall** [comment]
Hey all, I haven't been maintaining this, but I actually have a new database which I've been planning to replace the existing with. 

@kingthorin I'd definitely be interested in some actions to update the list.

**Comment by kingthorin** [comment]
Shoot me an email, my github username at gmail dot com

**Comment by kingthorin** [comment]
@iannuttall I'm still willing to help with some automation. It would require that you publish your scripts/sources as part of this repo. (Not sure what your thoughts are on that.)
